import re

from ai_agent.config import CODEX_TIMEOUT_SECONDS, GITHUB_BASE_BRANCH, GITHUB_REPOSITORY
from ai_agent.github import PullRequest, ensure_github_configured, github_request
from ai_agent.shell import run


def slugify_branch_name(change_description: str, prefix: str = "feature") -> str:
    validate_branch_prefix(prefix)
    slug = change_description.lower().strip()
    slug = re.sub(r"[^a-z0-9._/-]+", "-", slug)
    slug = re.sub(r"-{2,}", "-", slug).strip("-./")
    if not slug:
        slug = "change"
    branch_name = f"{prefix}/{slug[:80].strip('-./')}"
    validate_branch_name(branch_name)
    return branch_name


def validate_branch_prefix(prefix: str) -> None:
    if not re.fullmatch(r"[A-Za-z0-9._-]+", prefix):
        raise ValueError(f"Invalid branch prefix: {prefix}")


def validate_branch_name(branch_name: str) -> None:
    invalid = (
        branch_name.startswith("/")
        or branch_name.endswith("/")
        or branch_name.endswith(".")
        or ".." in branch_name
        or "@{" in branch_name
        or "\\" in branch_name
        or not re.fullmatch(r"[A-Za-z0-9._/-]+", branch_name)
    )
    if invalid:
        raise ValueError(f"Invalid branch name: {branch_name}")


def implement(plan: str, branch_name: str) -> None:
    validate_branch_name(branch_name)
    run(["git", "checkout", "main"])
    run(["git", "pull", "origin", "main"])
    run(["git", "checkout", "-b", branch_name])
    run(["codex", plan], timeout=CODEX_TIMEOUT_SECONDS)


def has_changes() -> bool:
    return bool(run(["git", "status", "--porcelain"]).output.strip())


def push(branch_name: str, change_name: str, commit_type: str = "feat") -> str:
    validate_branch_name(branch_name)
    if not has_changes():
        raise RuntimeError("Codex finished, but there are no repository changes to commit")
    run(["git", "add", "."])
    run(["git", "commit", "-m", f"{commit_type}: {change_name}"])
    run(["git", "push", "origin", branch_name])
    return run(["git", "rev-parse", "HEAD"]).output.strip()


def create_pull_request(
    branch_name: str,
    change_name: str,
    body_text: str,
    title_type: str = "feat",
    body_label: str = "Plan",
) -> PullRequest:
    ensure_github_configured()
    validate_branch_name(branch_name)
    payload = {
        "title": f"{title_type}: {change_name}",
        "head": branch_name,
        "base": GITHUB_BASE_BRANCH,
        "body": f"Generated by Channel Cast Agent.\n\n{body_label}:\n\n{body_text}",
        "maintainer_can_modify": True,
    }
    response = github_request("POST", f"/repos/{GITHUB_REPOSITORY}/pulls", payload)
    return PullRequest(
        number=int(response["number"]),
        url=response["html_url"],
        head_sha=response["head"]["sha"],
    )
